services:
  backend:
    build:
      context: .
      dockerfile: server/server.Dockerfile
    ports:
      - "2022:2022"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
    container_name: ${BACKEND_CONTAINER_NAME:-app-backend}
    depends_on:
      db-push:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2022/health"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  db-push:
    build:
      context: .
      dockerfile: server/server.Dockerfile
    container_name: ${DB_PUSH_CONTAINER_NAME:-app-db-push}
    command: ["bun", "run", "drizzle-kit", "push", "--force"]
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@postgres:5432/postgres}
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: client/client.Dockerfile
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - BACKEND_HOST=${BACKEND_CONTAINER_NAME:-app-backend}
    container_name: ${FRONTEND_CONTAINER_NAME:-app-frontend}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/index.html"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    image: postgres:17-alpine3.21
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 20s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: ${NETWORK_NAME:-app_network}
    driver: bridge
