name: Bug Report
description: Report a bug or issue with the app.build platform
title: "[Bug]: "
labels: ["bug", "Web"]
assignees:
  - pffigueiredo

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Brief, plain description of what went wrong
      placeholder: Describe what happened with as much detail as possible
    validations:
      required: true

  - type: input
    id: app-name
    attributes:
      label: App Name
      placeholder: e.g., simple-counter-e831
    validations:
      required: false

  - type: input
    id: app-id
    attributes:
      label: App ID
      placeholder: e.g., 7ebb87ae-0bdf-456b-a3e9-ae27851363d7
    validations:
      required: false

  - type: input
    id: trace-id
    attributes:
      label: Trace ID
      placeholder: e.g., trace-abc123def456
    validations:
      required: false

  - type: input
    id: tech-stack
    attributes:
      label: Tech Stack
      placeholder: e.g., trpc_agent
    validations:
      required: false

  - type: input
    id: deploy-status
    attributes:
      label: Deploy Status
      placeholder: e.g., deployed
    validations:
      required: false

  - type: input
    id: app-url
    attributes:
      label: App URL
      placeholder: https://your-app.com
    validations:
      required: false

  - type: input
    id: repository
    attributes:
      label: Repository
      placeholder: https://github.com/username/repo-name
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: e.g., Chrome 138.0.0.0
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., macOS 10.15.7
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        <details>
        <summary><b>App Info & Environment</b> (click to expand)</summary>

        - **App Name:** ${{ inputs.app-name }}
        - **App ID:** ${{ inputs.app-id }}
        - **Trace ID:** ${{ inputs.trace-id }}
        - **Tech Stack:** ${{ inputs.tech-stack }}
        - **Deploy Status:** ${{ inputs.deploy-status }}
        - **App URL:** ${{ inputs.app-url }}
        - **Repository:** ${{ inputs.repository }}
        - **Browser:** ${{ inputs.browser }}
        - **Operating System:** ${{ inputs.os }}

        </details>