name: Release CLI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release apps/cli
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write # Required for npm provenance

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for semantic-release to access full git history

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Release apps/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun run cli:release
